version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:3000"
    volumes:
      - ./src:/app/src
    environment:
      # This is Windows to work properly
      - CHOKIDAR_USEPOLLING=true
